version: "3.8"
services:
  frontend:
    build: ./frontend
    restart: always #change if you don't want your container restarting
    environment:
      - NODE_ENV=production
    ports:
      - 3001:3001
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always #change if you don't want your container restarting
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    depends_on:
      - postgres
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=replicate
    # mount ssl certificates
    #volumes:
    #  - ./nginx/certs:/etc/nginx/certs
  ngnix:
    build: ./nginx/
    depends_on:
      - backend
    ports:
      - 443:443
      - 80:80