version: "3.8"
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=replicate
    # mount ssl certificates
    #volumes:
    #  - ./nginx/certs:/etc/nginx/certs
